
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Siti Afiyah
 */
public class frmMain extends javax.swing.JFrame {

    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";
    
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpenerbit = new javax.swing.JTextField();
        txtkode = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtpengarang = new javax.swing.JTextField();
        txttanggal = new com.toedter.calendar.JDateChooser();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(218, 124, 124));
        jPanel1.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(238, 212, 216));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 0, 840, 10);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 130, 30);

        txtuser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtuser);
        txtuser.setBounds(60, 50, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Perpustakaan TSM 24");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 10, 270, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Malang");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 50, 70, 30);

        labeltanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labeltanggal.setForeground(new java.awt.Color(255, 255, 255));
        labeltanggal.setText("Tanggal");
        jPanel1.add(labeltanggal);
        labeltanggal.setBounds(680, 20, 120, 30);

        labeljam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labeljam.setForeground(new java.awt.Color(255, 255, 255));
        labeljam.setText("Jam");
        jPanel1.add(labeljam);
        labeljam.setBounds(680, 50, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 120);

        jPanel12.setBackground(new java.awt.Color(238, 212, 216));
        jPanel12.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(218, 124, 124));
        jPanel2.setLayout(null);
        jPanel12.add(jPanel2);
        jPanel2.setBounds(390, 0, 10, 430);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Kode Buku");
        jPanel12.add(jLabel6);
        jLabel6.setBounds(30, 110, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Pengarang");
        jPanel12.add(jLabel7);
        jLabel7.setBounds(30, 270, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Judul Buku");
        jPanel12.add(jLabel8);
        jLabel8.setBounds(30, 150, 90, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Tanggal Terbit");
        jPanel12.add(jLabel9);
        jLabel9.setBounds(30, 190, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Penerbit");
        jPanel12.add(jLabel10);
        jLabel10.setBounds(30, 230, 90, 30);
        jPanel12.add(txtpenerbit);
        txtpenerbit.setBounds(160, 230, 190, 30);
        jPanel12.add(txtkode);
        txtkode.setBounds(160, 110, 190, 30);
        jPanel12.add(txtjudul);
        txtjudul.setBounds(160, 150, 190, 30);
        jPanel12.add(txtpengarang);
        txtpengarang.setBounds(160, 270, 190, 30);
        jPanel12.add(txttanggal);
        txttanggal.setBounds(160, 190, 190, 30);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel12.add(clear);
        clear.setBounds(160, 330, 80, 30);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel12.add(save);
        save.setBounds(260, 330, 80, 30);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "kode_buku", "judul_buku", "tanggal", "penerbit", "pengarang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel12.add(jScrollPane1);
        jScrollPane1.setBounds(430, 100, 390, 260);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Cari Judul Buku");
        jPanel12.add(jLabel11);
        jLabel11.setBounds(430, 10, 130, 30);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton1);
        jButton1.setBounds(450, 380, 80, 30);

        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2);
        jButton2.setBounds(710, 50, 80, 30);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton3);
        jButton3.setBounds(630, 380, 80, 30);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton4);
        jButton4.setBounds(540, 380, 80, 30);

        jButton5.setText("Cetak");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton5);
        jButton5.setBounds(720, 380, 80, 30);
        jPanel12.add(txtcari);
        txtcari.setBounds(430, 50, 250, 30);

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Masukan Data Buku");
        jPanel12.add(jLabel12);
        jLabel12.setBounds(110, 40, 180, 30);

        jPanel3.setBackground(new java.awt.Color(218, 124, 124));
        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel13);
        jLabel13.setBounds(60, 60, 90, 30);

        jPanel12.add(jPanel3);
        jPanel3.setBounds(0, 0, 10, 440);

        jPanel4.setBackground(new java.awt.Color(218, 124, 124));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel14);
        jLabel14.setBounds(60, 60, 90, 30);

        jPanel12.add(jPanel4);
        jPanel4.setBounds(830, 0, 10, 430);

        jPanel5.setBackground(new java.awt.Color(218, 124, 124));
        jPanel5.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jLabel15);
        jLabel15.setBounds(60, 60, 90, 30);

        jPanel12.add(jPanel5);
        jPanel5.setBounds(0, 430, 840, 10);

        getContentPane().add(jPanel12);
        jPanel12.setBounds(0, 120, 840, 440);

        setBounds(0, 0, 856, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(txttanggal.getDate());

        Date tglmasuk = txttanggal.getDate();
        
        if ("".equals(txtkode.getText()) || "".equals(txtjudul.getText()) 
                || tanggal.equals("") || "".equals(txtpenerbit.getText())
                || "".equals(txtpengarang.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", 
            JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL = "INSERT INTO tb_buku (kode_buku,judul_buku,tanggal,penerbit,pengarang)"
                    +"VALUES('"+txtkode.getText()+"', '"+txtjudul.getText()+"', '"+tanggal+"', "
                    + "'"+txtpenerbit.getText()+"','"+txtpengarang.getText()+"')";
        
            int status = KoneksiDB.execute(SQL);
            
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", 
                JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", 
                JOptionPane.WARNING_MESSAGE);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        txtkode.setText("");
        txtjudul.setText("");
        txtpenerbit.setText("");
        txtpengarang.setText("");
        txttanggal.setDate(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MessageFormat header = new MessageFormat("Laporan Pendataan Buku");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if("".equals(txtkode.getText())|| "".equals(txtjudul.getText())||
            "".equals(txttanggal.getDate()) || "".equals(txtpenerbit.getText()) || 
            "".equals(txtpengarang.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = dateFormat.format(txttanggal.getDate());
                String SQL = "UPDATE tb_buku SET "
                       + "kode_buku='"+txtkode.getText()+"'"
                        + "judul_buku='"+txtjudul.getText()+"'"
                        + "tanggal='"+tanggal+"'"
                        + "penerbit='"+txtpenerbit.getText()+"'"
                        + "pengarang='" +txtpengarang.getText()+"'"
                        + "WHERE kode_buku='"+txtkode.getText()+"'";
                int status = KoneksiDB.execute(SQL);
                if (status == 1) {
                    JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
        }   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            txtkode.setText(tblData.getValueAt(baris, 0).toString());
            //txtkode.setEditable(false);
            txtjudul.setText(tblData.getValueAt(baris,1).toString());
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = tblData.getValueAt(baris, 2).toString();
            Date tgl;
            try {
                tgl = dateFormat.parse(tanggal);
                txttanggal.setDate(tgl);
            }catch (ParseException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null,ex);
            }
            txtpenerbit.setText(tblData.getValueAt(baris, 3).toString());
            txtpengarang.setText(tblData.getValueAt(baris, 4).toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != -1){
            String kode_buku = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_buku WHERE kode_buku='"+kode_buku+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(this, "data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tabelTampil1 = new DefaultTableModel();
        tabelTampil1.addColumn("kode_buku");
        tabelTampil1.addColumn("judul_buku");
        tabelTampil1.addColumn("tanggal");
        tabelTampil1.addColumn("penerbit");
        tabelTampil1.addColumn("pengarang");
        
        String jdl = txtcari.getText();
        try{ 
            String sql = "Select * from tb_buku where judul_buku like '%" + jdl + "%'";
            ResultSet rs = KoneksiDB.executeQuery(sql);
            while (rs.next()) {
            tabelTampil1.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
            });
            }
            tblData.setModel(tabelTampil1);
                }catch (SQLException ex){
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String user1 = login.user;
       txtuser.setText(user1);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    public void setTanggal(){
           java.util.Date skrg = new java.util.Date();
           java.text.SimpleDateFormat kal = new
           java.text.SimpleDateFormat("dd/MM/yyyy");
           labeltanggal.setText(kal.format(skrg));
       } 
    
    public void setJam() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }    
                    String jam = nol_jam + Integer.toString(nilai_jam);
                    String menit = nol_menit + Integer.toString(nilai_menit);
                    String detik = nol_detik + Integer.toString(nilai_detik);
                    labeljam.setText("Jam " +jam+ ":" +menit+ ":" +detik);
                }
         };
        new Timer(100, taskPerformer).start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JButton save;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private com.toedter.calendar.JDateChooser txttanggal;
    private javax.swing.JLabel txtuser;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"kode_buku","judul_buku","tanggal","penerbit","pengarang"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_buku";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try{
            while(rs.next()){
                String kode_buku = rs.getString(1);
                String judul_buku = rs.getString(2);
                String tanggal = rs.getString(3);
                String penerbit = rs.getString(4);
                String pengarang = rs.getString(5);

                String data[] = {kode_buku,judul_buku,tanggal,penerbit,pengarang};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
           // Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);//To change body of generated methods, choose Tools | Templates.
    }
}
